// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package badgeforce_pb is a generated protocol buffer package.

It is generated from these files:
	account.proto
	payload.proto

It has these top-level messages:
	Account
	Payload
	AnyData
	StorePublicDataPayload
*/
package badgeforce_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account_EntityType int32

const (
	Account_PERSON       Account_EntityType = 0
	Account_ORGANIZATION Account_EntityType = 1
)

var Account_EntityType_name = map[int32]string{
	0: "PERSON",
	1: "ORGANIZATION",
}
var Account_EntityType_value = map[string]int32{
	"PERSON":       0,
	"ORGANIZATION": 1,
}

func (x Account_EntityType) String() string {
	return proto.EnumName(Account_EntityType_name, int32(x))
}
func (Account_EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Account struct {
	PublicKey  string              `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	PublicData *Account_PublicData `protobuf:"bytes,2,opt,name=publicData" json:"publicData,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Account) GetPublicData() *Account_PublicData {
	if m != nil {
		return m.PublicData
	}
	return nil
}

type Account_PublicData struct {
	Number      string             `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	DateOfBirth string             `protobuf:"bytes,2,opt,name=dateOfBirth" json:"dateOfBirth,omitempty"`
	Address     string             `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Photo       string             `protobuf:"bytes,4,opt,name=photo" json:"photo,omitempty"`
	Url         string             `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Name        string             `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Type        Account_EntityType `protobuf:"varint,7,opt,name=type,enum=badgeforce_pb.Account_EntityType" json:"type,omitempty"`
}

func (m *Account_PublicData) Reset()                    { *m = Account_PublicData{} }
func (m *Account_PublicData) String() string            { return proto.CompactTextString(m) }
func (*Account_PublicData) ProtoMessage()               {}
func (*Account_PublicData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Account_PublicData) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Account_PublicData) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *Account_PublicData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account_PublicData) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Account_PublicData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Account_PublicData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account_PublicData) GetType() Account_EntityType {
	if m != nil {
		return m.Type
	}
	return Account_PERSON
}

func init() {
	proto.RegisterType((*Account)(nil), "badgeforce_pb.Account")
	proto.RegisterType((*Account_PublicData)(nil), "badgeforce_pb.Account.PublicData")
	proto.RegisterEnum("badgeforce_pb.Account_EntityType", Account_EntityType_name, Account_EntityType_value)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x36, 0x4d, 0xc8, 0xd4, 0x4a, 0x18, 0x44, 0x16, 0xf1, 0x10, 0x7b, 0x0a, 0x1e,
	0x72, 0x50, 0x7c, 0x80, 0x88, 0x45, 0x8a, 0x90, 0x94, 0xb5, 0x27, 0x2f, 0xb2, 0x49, 0xb6, 0x36,
	0xd0, 0x66, 0x97, 0xed, 0xe6, 0x90, 0xe7, 0xf4, 0x35, 0x7c, 0x08, 0x71, 0x13, 0x4d, 0x3d, 0x78,
	0x9b, 0xef, 0x9b, 0x7f, 0x67, 0x58, 0x06, 0x66, 0xbc, 0x28, 0x64, 0x53, 0x9b, 0x58, 0x69, 0x69,
	0x24, 0xce, 0x72, 0x5e, 0xbe, 0x8b, 0x8d, 0xd4, 0x85, 0x78, 0x53, 0xf9, 0xfc, 0x73, 0x04, 0x5e,
	0xd2, 0x05, 0xf0, 0x0a, 0x7c, 0xd5, 0xe4, 0xbb, 0xaa, 0x78, 0x16, 0x2d, 0x25, 0x21, 0x89, 0x7c,
	0x36, 0x08, 0x4c, 0x00, 0x3a, 0x78, 0xe4, 0x86, 0xd3, 0x51, 0x48, 0xa2, 0xe9, 0xed, 0x75, 0xfc,
	0x67, 0x5a, 0xdc, 0x4f, 0x8a, 0x57, 0xbf, 0x41, 0x76, 0xf4, 0xe8, 0xf2, 0x83, 0x00, 0x0c, 0x2d,
	0xbc, 0x00, 0xb7, 0x6e, 0xf6, 0xb9, 0xd0, 0xfd, 0xb2, 0x9e, 0x30, 0x84, 0x69, 0xc9, 0x8d, 0xc8,
	0x36, 0x0f, 0x95, 0x36, 0x5b, 0xbb, 0xca, 0x67, 0xc7, 0x0a, 0x29, 0x78, 0xbc, 0x2c, 0xb5, 0x38,
	0x1c, 0xe8, 0xd8, 0x76, 0x7f, 0x10, 0xcf, 0x61, 0xa2, 0xb6, 0xd2, 0x48, 0xea, 0x58, 0xdf, 0x01,
	0x06, 0x30, 0x6e, 0xf4, 0x8e, 0x4e, 0xac, 0xfb, 0x2e, 0x11, 0xc1, 0xa9, 0xf9, 0x5e, 0x50, 0xd7,
	0x2a, 0x5b, 0xe3, 0x3d, 0x38, 0xa6, 0x55, 0x82, 0x7a, 0x21, 0x89, 0xce, 0xfe, 0xfd, 0xdb, 0xa2,
	0x36, 0x95, 0x69, 0xd7, 0xad, 0x12, 0xcc, 0xc6, 0xe7, 0x37, 0x00, 0x83, 0x43, 0x00, 0x77, 0xb5,
	0x60, 0x2f, 0x59, 0x1a, 0x9c, 0x60, 0x00, 0xa7, 0x19, 0x7b, 0x4a, 0xd2, 0xe5, 0x6b, 0xb2, 0x5e,
	0x66, 0x69, 0x40, 0x72, 0xd7, 0x1e, 0xe1, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x21, 0x42,
	0xb6, 0x95, 0x01, 0x00, 0x00,
}
