# Copyright 2017 Intel Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# docker build -f compose-network/badgeforce/nginx/Dockerfile -t reverse-proxy ./compose-network/badgeforce/nginx

version: "3.5"

services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  ipfs-node:
    image: jbenet/go-ipfs:latest
    container_name: ipfs-node
    restart: always
    expose:
      - 8080
      - 4001
      - 5001
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    networks: 
      - badgeforce-blockchain
  
  badgeforce-accounts:
    image: badgeforce-accounts:latest
    depends_on:
      - validator
    container_name: badgeforce-accounts-latest
    entrypoint: "bash -c \"\
          ./accounts_transaction_processor -vv -C tcp://validator:4004\
        \""
    networks: 
      - badgeforce-blockchain
  
  badgeforce-issuer:
    image: badgeforce-issuer:latest
    depends_on:
      - validator
    container_name: badgeforce-issuer-latest
    entrypoint: "bash -c \"\
          ./badgeforce-issuer run --verbosity 2 --validator tcp://validator:4004 --ipfs-node http://ipfs-node:5001\
        \""
    networks: 
      - badgeforce-blockchain


  validator:
    image: hyperledger/sawtooth-validator
    restart: always
    container_name: sawtooth-validator-default
    expose:
      - 4004
      - 8800
    volumes: 
      - ./config.sh:/badgeforce/configuration/config.sh
    ports:
      - "4004:4004"
      - "8800:8800"
    entrypoint: "bash -c \"\
        ./badgeforce/configuration/config.sh && \
        sawtooth-validator -vv \
          --endpoint tcp://ec2-54-210-230-199.compute-1.amazonaws.com:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --network-auth trust \
        \""
    networks: 
      - badgeforce-blockchain

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default
    expose: 
      - 8008
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008
    environment:
      - VIRTUAL_HOST=rest-api:8008
      - VIRTUAL_PORT=8008
      - LETSENCRYPT_HOST=testnet.badgeforce.io
      - LETSENCRYPT_EMAIL=engineering@badgeforce.io
    networks: 
      - badgeforce-blockchain

  shell:
    image: hyperledger/sawtooth-all:1.0
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
    networks: 
      - badgeforce-blockchain

networks: 
  default:
    external:
      name: nginx-proxy
  badgeforce-blockchain:
    name: badgeforce-blockchain
