/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.badgeforce_pb.Credential', null, global);
goog.exportSymbol('proto.badgeforce_pb.Template', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.badgeforce_pb.Credential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.badgeforce_pb.Credential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.badgeforce_pb.Credential.displayName = 'proto.badgeforce_pb.Credential';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.badgeforce_pb.Credential.prototype.toObject = function(opt_includeInstance) {
  return proto.badgeforce_pb.Credential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.badgeforce_pb.Credential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Credential.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    issuerPublicKey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    recipientPublicKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    revokationStatus: jspb.Message.getFieldWithDefault(msg, 4, false),
    proofOfIntegrityHash: jspb.Message.getFieldWithDefault(msg, 5, ""),
    storageHash: jspb.Message.getFieldWithDefault(msg, 6, ""),
    template: (f = msg.getTemplate()) && proto.badgeforce_pb.Template.toObject(includeInstance, f),
    expiration: jspb.Message.getFieldWithDefault(msg, 8, 0),
    issuedAt: jspb.Message.getFieldWithDefault(msg, 9, 0),
    signature: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.badgeforce_pb.Credential}
 */
proto.badgeforce_pb.Credential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.badgeforce_pb.Credential;
  return proto.badgeforce_pb.Credential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.badgeforce_pb.Credential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.badgeforce_pb.Credential}
 */
proto.badgeforce_pb.Credential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuerPublicKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRecipientPublicKey(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRevokationStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProofOfIntegrityHash(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStorageHash(value);
      break;
    case 7:
      var value = new proto.badgeforce_pb.Template;
      reader.readMessage(value,proto.badgeforce_pb.Template.deserializeBinaryFromReader);
      msg.setTemplate(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiration(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIssuedAt(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.badgeforce_pb.Credential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.badgeforce_pb.Credential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.badgeforce_pb.Credential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Credential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIssuerPublicKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRecipientPublicKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRevokationStatus();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getProofOfIntegrityHash();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStorageHash();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTemplate();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.badgeforce_pb.Template.serializeBinaryToWriter
    );
  }
  f = message.getExpiration();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getIssuedAt();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string issuer_public_key = 2;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getIssuerPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setIssuerPublicKey = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string recipient_public_key = 3;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getRecipientPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setRecipientPublicKey = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool revokation_status = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.badgeforce_pb.Credential.prototype.getRevokationStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.badgeforce_pb.Credential.prototype.setRevokationStatus = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string proof_of_integrity_hash = 5;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getProofOfIntegrityHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setProofOfIntegrityHash = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string storage_hash = 6;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getStorageHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setStorageHash = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional Template template = 7;
 * @return {?proto.badgeforce_pb.Template}
 */
proto.badgeforce_pb.Credential.prototype.getTemplate = function() {
  return /** @type{?proto.badgeforce_pb.Template} */ (
    jspb.Message.getWrapperField(this, proto.badgeforce_pb.Template, 7));
};


/** @param {?proto.badgeforce_pb.Template|undefined} value */
proto.badgeforce_pb.Credential.prototype.setTemplate = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.badgeforce_pb.Credential.prototype.clearTemplate = function() {
  this.setTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.badgeforce_pb.Credential.prototype.hasTemplate = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int64 expiration = 8;
 * @return {number}
 */
proto.badgeforce_pb.Credential.prototype.getExpiration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.badgeforce_pb.Credential.prototype.setExpiration = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 issued_at = 9;
 * @return {number}
 */
proto.badgeforce_pb.Credential.prototype.getIssuedAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.badgeforce_pb.Credential.prototype.setIssuedAt = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string signature = 10;
 * @return {string}
 */
proto.badgeforce_pb.Credential.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Credential.prototype.setSignature = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.badgeforce_pb.Template = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.badgeforce_pb.Template, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.badgeforce_pb.Template.displayName = 'proto.badgeforce_pb.Template';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.badgeforce_pb.Template.prototype.toObject = function(opt_includeInstance) {
  return proto.badgeforce_pb.Template.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.badgeforce_pb.Template} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Template.toObject = function(includeInstance, msg) {
  var f, obj = {
    owner: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    version: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.badgeforce_pb.Template}
 */
proto.badgeforce_pb.Template.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.badgeforce_pb.Template;
  return proto.badgeforce_pb.Template.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.badgeforce_pb.Template} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.badgeforce_pb.Template}
 */
proto.badgeforce_pb.Template.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwner(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.badgeforce_pb.Template.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.badgeforce_pb.Template.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.badgeforce_pb.Template} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.badgeforce_pb.Template.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string owner = 1;
 * @return {string}
 */
proto.badgeforce_pb.Template.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Template.prototype.setOwner = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.badgeforce_pb.Template.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Template.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.badgeforce_pb.Template.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.badgeforce_pb.Template.prototype.setVersion = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.badgeforce_pb);
