# Copyright 2017 Intel Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3.5"

services:
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-peer
    depends_on:
      - peer-validator
    entrypoint: settings-tp -vv -C tcp://peer-validator:4005
    stop_signal: SIGKILL

  peer-validator:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-default-peer
    expose:
      - 4005
      - 8801
    volumes: 
      - ./config.sh:/badgeforce/configuration/config.sh
    ports:
      - "8801:8800"
      - "4005:4005"
    entrypoint: "bash -c \"\
        ./badgeforce/configuration/config.sh && \
        sawtooth-validator -vv \
          --endpoint tcp://peer-validator:8800 \
          --bind component:tcp://eth0:4005 \
          --bind network:tcp://eth0:8800 \
          --peers tcp://127.0.0.1:8802 \
        \""
    networks: 
      - badgeforce-peer
    stop_signal: SIGKILL

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-peer
    ports:
      - "8009:8009"
    depends_on:
      - peer-validator
    entrypoint: sawtooth-rest-api -C tcp://peer-validator:4005 --bind rest-api:8009
    networks: 
      - badgeforce-peer
    stop_signal: SIGKILL

networks: 
  badgeforce-peer:
    name: badgeforce-peer