// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ci_payload.proto

package badgeforce_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CredentialIssuingMethod int32

const (
	CredentialIssuingMethod_ISSUE  CredentialIssuingMethod = 0
	CredentialIssuingMethod_REVOKE CredentialIssuingMethod = 1
)

var CredentialIssuingMethod_name = map[int32]string{
	0: "ISSUE",
	1: "REVOKE",
}
var CredentialIssuingMethod_value = map[string]int32{
	"ISSUE":  0,
	"REVOKE": 1,
}

func (x CredentialIssuingMethod) String() string {
	return proto.EnumName(CredentialIssuingMethod_name, int32(x))
}
func (CredentialIssuingMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ci_payload_eef69235cbe77d4b, []int{0}
}

type CredentialIssuingRPCRequest struct {
	// Types that are valid to be assigned to Method:
	//	*CredentialIssuingRPCRequest_Issue
	//	*CredentialIssuingRPCRequest_Revoke
	Method               isCredentialIssuingRPCRequest_Method `protobuf_oneof:"method"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *CredentialIssuingRPCRequest) Reset()         { *m = CredentialIssuingRPCRequest{} }
func (m *CredentialIssuingRPCRequest) String() string { return proto.CompactTextString(m) }
func (*CredentialIssuingRPCRequest) ProtoMessage()    {}
func (*CredentialIssuingRPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ci_payload_eef69235cbe77d4b, []int{0}
}
func (m *CredentialIssuingRPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialIssuingRPCRequest.Unmarshal(m, b)
}
func (m *CredentialIssuingRPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialIssuingRPCRequest.Marshal(b, m, deterministic)
}
func (dst *CredentialIssuingRPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialIssuingRPCRequest.Merge(dst, src)
}
func (m *CredentialIssuingRPCRequest) XXX_Size() int {
	return xxx_messageInfo_CredentialIssuingRPCRequest.Size(m)
}
func (m *CredentialIssuingRPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialIssuingRPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialIssuingRPCRequest proto.InternalMessageInfo

type isCredentialIssuingRPCRequest_Method interface {
	isCredentialIssuingRPCRequest_Method()
}

type CredentialIssuingRPCRequest_Issue struct {
	Issue *Issue `protobuf:"bytes,1,opt,name=issue,proto3,oneof"`
}

type CredentialIssuingRPCRequest_Revoke struct {
	Revoke *Revoke `protobuf:"bytes,2,opt,name=revoke,proto3,oneof"`
}

func (*CredentialIssuingRPCRequest_Issue) isCredentialIssuingRPCRequest_Method() {}

func (*CredentialIssuingRPCRequest_Revoke) isCredentialIssuingRPCRequest_Method() {}

func (m *CredentialIssuingRPCRequest) GetMethod() isCredentialIssuingRPCRequest_Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *CredentialIssuingRPCRequest) GetIssue() *Issue {
	if x, ok := m.GetMethod().(*CredentialIssuingRPCRequest_Issue); ok {
		return x.Issue
	}
	return nil
}

func (m *CredentialIssuingRPCRequest) GetRevoke() *Revoke {
	if x, ok := m.GetMethod().(*CredentialIssuingRPCRequest_Revoke); ok {
		return x.Revoke
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CredentialIssuingRPCRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CredentialIssuingRPCRequest_OneofMarshaler, _CredentialIssuingRPCRequest_OneofUnmarshaler, _CredentialIssuingRPCRequest_OneofSizer, []interface{}{
		(*CredentialIssuingRPCRequest_Issue)(nil),
		(*CredentialIssuingRPCRequest_Revoke)(nil),
	}
}

func _CredentialIssuingRPCRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CredentialIssuingRPCRequest)
	// method
	switch x := m.Method.(type) {
	case *CredentialIssuingRPCRequest_Issue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Issue); err != nil {
			return err
		}
	case *CredentialIssuingRPCRequest_Revoke:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Revoke); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CredentialIssuingRPCRequest.Method has unexpected type %T", x)
	}
	return nil
}

func _CredentialIssuingRPCRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CredentialIssuingRPCRequest)
	switch tag {
	case 1: // method.issue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Issue)
		err := b.DecodeMessage(msg)
		m.Method = &CredentialIssuingRPCRequest_Issue{msg}
		return true, err
	case 2: // method.revoke
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Revoke)
		err := b.DecodeMessage(msg)
		m.Method = &CredentialIssuingRPCRequest_Revoke{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CredentialIssuingRPCRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CredentialIssuingRPCRequest)
	// method
	switch x := m.Method.(type) {
	case *CredentialIssuingRPCRequest_Issue:
		s := proto.Size(x.Issue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CredentialIssuingRPCRequest_Revoke:
		s := proto.Size(x.Revoke)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Issue struct {
	Params               *Credential `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ci_payload_eef69235cbe77d4b, []int{1}
}
func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (dst *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(dst, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetParams() *Credential {
	if m != nil {
		return m.Params
	}
	return nil
}

type Revoke struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Revoke) Reset()         { *m = Revoke{} }
func (m *Revoke) String() string { return proto.CompactTextString(m) }
func (*Revoke) ProtoMessage()    {}
func (*Revoke) Descriptor() ([]byte, []int) {
	return fileDescriptor_ci_payload_eef69235cbe77d4b, []int{2}
}
func (m *Revoke) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Revoke.Unmarshal(m, b)
}
func (m *Revoke) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Revoke.Marshal(b, m, deterministic)
}
func (dst *Revoke) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Revoke.Merge(dst, src)
}
func (m *Revoke) XXX_Size() int {
	return xxx_messageInfo_Revoke.Size(m)
}
func (m *Revoke) XXX_DiscardUnknown() {
	xxx_messageInfo_Revoke.DiscardUnknown(m)
}

var xxx_messageInfo_Revoke proto.InternalMessageInfo

func (m *Revoke) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*CredentialIssuingRPCRequest)(nil), "badgeforce_pb.CredentialIssuingRPCRequest")
	proto.RegisterType((*Issue)(nil), "badgeforce_pb.Issue")
	proto.RegisterType((*Revoke)(nil), "badgeforce_pb.Revoke")
	proto.RegisterEnum("badgeforce_pb.CredentialIssuingMethod", CredentialIssuingMethod_name, CredentialIssuingMethod_value)
}

func init() { proto.RegisterFile("ci_payload.proto", fileDescriptor_ci_payload_eef69235cbe77d4b) }

var fileDescriptor_ci_payload_eef69235cbe77d4b = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0x8c, 0x2f,
	0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x4a,
	0x4c, 0x49, 0x4f, 0x4d, 0xcb, 0x2f, 0x4a, 0x4e, 0x8d, 0x2f, 0x48, 0x92, 0x12, 0x48, 0x2e, 0x4a,
	0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0x81, 0x28, 0x50, 0x6a, 0x63, 0xe4, 0x92, 0x76, 0x86,
	0x0b, 0x7a, 0x16, 0x17, 0x97, 0x66, 0xe6, 0xa5, 0x07, 0x05, 0x38, 0x07, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0xe9, 0x70, 0xb1, 0x66, 0x16, 0x17, 0x97, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x1b, 0x89, 0xe8, 0xa1, 0x18, 0xa8, 0x07, 0xd2, 0x90, 0xea, 0xc1, 0x10, 0x04, 0x51, 0x24,
	0xa4, 0xcf, 0xc5, 0x56, 0x94, 0x5a, 0x96, 0x9f, 0x9d, 0x2a, 0xc1, 0x04, 0x56, 0x2e, 0x8a, 0xa6,
	0x3c, 0x08, 0x2c, 0xe9, 0xc1, 0x10, 0x04, 0x55, 0xe6, 0xc4, 0xc1, 0xc5, 0x96, 0x9b, 0x5a, 0x92,
	0x91, 0x9f, 0xa2, 0x64, 0xc5, 0xc5, 0x0a, 0x36, 0x4c, 0xc8, 0x90, 0x8b, 0xad, 0x20, 0xb1, 0x28,
	0x31, 0xb7, 0x18, 0x6a, 0xa5, 0x24, 0x9a, 0x19, 0x08, 0xd7, 0x06, 0x41, 0x15, 0x2a, 0xa9, 0x71,
	0xb1, 0x41, 0x4c, 0x16, 0x92, 0xe1, 0xe2, 0x4c, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x4e, 0x05,
	0xe9, 0x67, 0xd6, 0xe0, 0x0c, 0x42, 0x08, 0x68, 0x19, 0x70, 0x89, 0x63, 0xf8, 0xd5, 0x17, 0x6c,
	0xbd, 0x10, 0x27, 0x17, 0xab, 0x67, 0x70, 0x70, 0xa8, 0xab, 0x00, 0x83, 0x10, 0x17, 0x17, 0x5b,
	0x90, 0x6b, 0x98, 0xbf, 0xb7, 0xab, 0x00, 0xa3, 0x13, 0x7f, 0x14, 0x6a, 0x08, 0x26, 0xb1, 0x81,
	0x83, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x74, 0x92, 0x31, 0x80, 0x6b, 0x01, 0x00, 0x00,
}
