// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credential.proto

package badgeforce_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credential struct {
	Data                 *CredentialData         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Verification         *CredentialVerification `protobuf:"bytes,2,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_35626368841070b2, []int{0}
}
func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (dst *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(dst, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetData() *CredentialData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Credential) GetVerification() *CredentialVerification {
	if m != nil {
		return m.Verification
	}
	return nil
}

type CredentialData struct {
	Template             *Template       `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	RecipientPub         string          `protobuf:"bytes,2,opt,name=recipient_pub,json=recipientPub,proto3" json:"recipient_pub,omitempty"`
	DateEarned           string          `protobuf:"bytes,3,opt,name=date_earned,json=dateEarned,proto3" json:"date_earned,omitempty"`
	CoreData             *_struct.Struct `protobuf:"bytes,4,opt,name=core_data,json=coreData,proto3" json:"core_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CredentialData) Reset()         { *m = CredentialData{} }
func (m *CredentialData) String() string { return proto.CompactTextString(m) }
func (*CredentialData) ProtoMessage()    {}
func (*CredentialData) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_35626368841070b2, []int{1}
}
func (m *CredentialData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialData.Unmarshal(m, b)
}
func (m *CredentialData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialData.Marshal(b, m, deterministic)
}
func (dst *CredentialData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialData.Merge(dst, src)
}
func (m *CredentialData) XXX_Size() int {
	return xxx_messageInfo_CredentialData.Size(m)
}
func (m *CredentialData) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialData.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialData proto.InternalMessageInfo

func (m *CredentialData) GetTemplate() *Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *CredentialData) GetRecipientPub() string {
	if m != nil {
		return m.RecipientPub
	}
	return ""
}

func (m *CredentialData) GetDateEarned() string {
	if m != nil {
		return m.DateEarned
	}
	return ""
}

func (m *CredentialData) GetCoreData() *_struct.Struct {
	if m != nil {
		return m.CoreData
	}
	return nil
}

type CredentialVerification struct {
	RecipientPub         string               `protobuf:"bytes,1,opt,name=recipient_pub,json=recipientPub,proto3" json:"recipient_pub,omitempty"`
	IssuerPub            string               `protobuf:"bytes,2,opt,name=issuer_pub,json=issuerPub,proto3" json:"issuer_pub,omitempty"`
	Signature            string               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ProofOfIntegrityHash string               `protobuf:"bytes,4,opt,name=proof_of_integrity_hash,json=proofOfIntegrityHash,proto3" json:"proof_of_integrity_hash,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	RevocationStatus     *RevocationStatus    `protobuf:"bytes,6,opt,name=revocation_status,json=revocationStatus,proto3" json:"revocation_status,omitempty"`
	IpfsHash             string               `protobuf:"bytes,7,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	IpfsFileName         string               `protobuf:"bytes,8,opt,name=ipfs_file_name,json=ipfsFileName,proto3" json:"ipfs_file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CredentialVerification) Reset()         { *m = CredentialVerification{} }
func (m *CredentialVerification) String() string { return proto.CompactTextString(m) }
func (*CredentialVerification) ProtoMessage()    {}
func (*CredentialVerification) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_35626368841070b2, []int{2}
}
func (m *CredentialVerification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialVerification.Unmarshal(m, b)
}
func (m *CredentialVerification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialVerification.Marshal(b, m, deterministic)
}
func (dst *CredentialVerification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialVerification.Merge(dst, src)
}
func (m *CredentialVerification) XXX_Size() int {
	return xxx_messageInfo_CredentialVerification.Size(m)
}
func (m *CredentialVerification) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialVerification.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialVerification proto.InternalMessageInfo

func (m *CredentialVerification) GetRecipientPub() string {
	if m != nil {
		return m.RecipientPub
	}
	return ""
}

func (m *CredentialVerification) GetIssuerPub() string {
	if m != nil {
		return m.IssuerPub
	}
	return ""
}

func (m *CredentialVerification) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CredentialVerification) GetProofOfIntegrityHash() string {
	if m != nil {
		return m.ProofOfIntegrityHash
	}
	return ""
}

func (m *CredentialVerification) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *CredentialVerification) GetRevocationStatus() *RevocationStatus {
	if m != nil {
		return m.RevocationStatus
	}
	return nil
}

func (m *CredentialVerification) GetIpfsHash() string {
	if m != nil {
		return m.IpfsHash
	}
	return ""
}

func (m *CredentialVerification) GetIpfsFileName() string {
	if m != nil {
		return m.IpfsFileName
	}
	return ""
}

type RevocationStatus struct {
	IsRevoked            bool                 `protobuf:"varint,1,opt,name=isRevoked,proto3" json:"isRevoked,omitempty"`
	RevokedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=revokedAt,proto3" json:"revokedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RevocationStatus) Reset()         { *m = RevocationStatus{} }
func (m *RevocationStatus) String() string { return proto.CompactTextString(m) }
func (*RevocationStatus) ProtoMessage()    {}
func (*RevocationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_35626368841070b2, []int{3}
}
func (m *RevocationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevocationStatus.Unmarshal(m, b)
}
func (m *RevocationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevocationStatus.Marshal(b, m, deterministic)
}
func (dst *RevocationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevocationStatus.Merge(dst, src)
}
func (m *RevocationStatus) XXX_Size() int {
	return xxx_messageInfo_RevocationStatus.Size(m)
}
func (m *RevocationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RevocationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RevocationStatus proto.InternalMessageInfo

func (m *RevocationStatus) GetIsRevoked() bool {
	if m != nil {
		return m.IsRevoked
	}
	return false
}

func (m *RevocationStatus) GetRevokedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Credential)(nil), "badgeforce_pb.Credential")
	proto.RegisterType((*CredentialData)(nil), "badgeforce_pb.CredentialData")
	proto.RegisterType((*CredentialVerification)(nil), "badgeforce_pb.CredentialVerification")
	proto.RegisterType((*RevocationStatus)(nil), "badgeforce_pb.RevocationStatus")
}

func init() { proto.RegisterFile("credential.proto", fileDescriptor_credential_35626368841070b2) }

var fileDescriptor_credential_35626368841070b2 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x25, 0xb5, 0xd6, 0xe4, 0xb6, 0x5d, 0xd7, 0x41, 0x6c, 0x58, 0x5b, 0x56, 0x56, 0x05, 0x9f,
	0x52, 0xb4, 0x0a, 0xe2, 0x9b, 0x9f, 0x58, 0x10, 0x95, 0x69, 0xf1, 0xc1, 0x97, 0x30, 0x49, 0x6e,
	0xb2, 0xa3, 0x49, 0x26, 0xcc, 0xdc, 0x14, 0xfd, 0x0b, 0xfe, 0x2b, 0xff, 0x98, 0x48, 0x66, 0xb2,
	0x5f, 0x69, 0xf5, 0x6d, 0xf7, 0x9c, 0x73, 0xe7, 0x9e, 0x73, 0x66, 0x02, 0xe3, 0x54, 0x63, 0x86,
	0x35, 0x49, 0x51, 0x46, 0x8d, 0x56, 0xa4, 0xd8, 0x7e, 0x22, 0xb2, 0x02, 0x73, 0xa5, 0x53, 0x8c,
	0x9b, 0x64, 0x32, 0x22, 0xac, 0x9a, 0x52, 0x10, 0x3a, 0x7a, 0x72, 0x58, 0x28, 0x55, 0x94, 0x78,
	0x6c, 0xff, 0x25, 0x6d, 0x7e, 0x6c, 0x48, 0xb7, 0x29, 0xf5, 0xec, 0x74, 0xc8, 0x92, 0xac, 0xd0,
	0x90, 0xa8, 0x1a, 0x27, 0x98, 0xfd, 0xf2, 0x00, 0x5e, 0x2f, 0x57, 0xb2, 0xc7, 0xb0, 0x9d, 0x09,
	0x12, 0xa1, 0x77, 0xcf, 0x7b, 0xb4, 0xfb, 0xe4, 0x28, 0xda, 0xd8, 0x1d, 0xad, 0x84, 0x6f, 0x04,
	0x09, 0x6e, 0xa5, 0xec, 0x14, 0xf6, 0x2e, 0x50, 0xcb, 0x5c, 0xa6, 0x82, 0xa4, 0xaa, 0xc3, 0x2d,
	0x3b, 0xfa, 0xf0, 0x9f, 0xa3, 0x5f, 0xd6, 0xc4, 0x7c, 0x63, 0x74, 0xf6, 0xdb, 0x83, 0xd1, 0xe6,
	0x0e, 0x76, 0x02, 0xfe, 0x22, 0x70, 0x6f, 0xea, 0x60, 0x70, 0xf2, 0x79, 0x4f, 0xf3, 0xa5, 0x90,
	0xdd, 0x87, 0x7d, 0x8d, 0xa9, 0x6c, 0x24, 0xd6, 0x14, 0x37, 0x6d, 0x62, 0x3d, 0x05, 0x7c, 0x6f,
	0x09, 0x7e, 0x6e, 0x13, 0x36, 0x85, 0xdd, 0x4c, 0x10, 0xc6, 0x28, 0x74, 0x8d, 0x59, 0x78, 0xcd,
	0x4a, 0xa0, 0x83, 0xde, 0x5a, 0x84, 0x3d, 0x85, 0x20, 0x55, 0x1a, 0x63, 0x5b, 0xc8, 0x76, 0xbf,
	0xdb, 0xf5, 0x19, 0x2d, 0xfa, 0x8c, 0xce, 0x6c, 0xdb, 0xdc, 0xef, 0x94, 0x9d, 0xe1, 0xd9, 0x9f,
	0x2d, 0xb8, 0x73, 0x75, 0xd8, 0xcb, 0xb6, 0xbc, 0x2b, 0x6c, 0x1d, 0x01, 0x48, 0x63, 0x5a, 0xd4,
	0x6b, 0xc6, 0x03, 0x87, 0x74, 0xf4, 0x21, 0x04, 0x46, 0x16, 0xb5, 0xa0, 0x56, 0x63, 0xef, 0x79,
	0x05, 0xb0, 0x67, 0x70, 0xd0, 0x68, 0xa5, 0xf2, 0x58, 0xe5, 0xb1, 0xac, 0x09, 0x0b, 0x2d, 0xe9,
	0x67, 0x3c, 0x17, 0x66, 0x6e, 0x03, 0x04, 0xfc, 0xb6, 0xa5, 0x3f, 0xe5, 0xa7, 0x0b, 0xf2, 0xbd,
	0x30, 0x73, 0xf6, 0x02, 0x00, 0x7f, 0x34, 0x52, 0xbb, 0x0b, 0xbc, 0x6e, 0xa3, 0x4e, 0x2e, 0x45,
	0x3d, 0x5f, 0x3c, 0x1d, 0xbe, 0xa6, 0x66, 0x1f, 0xe0, 0x96, 0xc6, 0x0b, 0xe5, 0x22, 0xc6, 0x86,
	0x04, 0xb5, 0x26, 0xdc, 0xb1, 0x47, 0x4c, 0x07, 0x37, 0xc5, 0x97, 0xba, 0x33, 0x2b, 0xe3, 0x63,
	0x3d, 0x40, 0xd8, 0x5d, 0x08, 0x64, 0x93, 0x1b, 0x67, 0xf9, 0x86, 0xb5, 0xec, 0x77, 0x80, 0xb5,
	0xf9, 0x00, 0x46, 0x96, 0xcc, 0x65, 0x89, 0x71, 0x2d, 0x2a, 0x0c, 0x7d, 0x57, 0x60, 0x87, 0xbe,
	0x93, 0x25, 0x7e, 0x14, 0x15, 0xce, 0xbe, 0xc1, 0x78, 0xb8, 0xa8, 0x6b, 0x4d, 0x9a, 0x0e, 0xfd,
	0x8e, 0x99, 0x6d, 0xdd, 0xe7, 0x2b, 0x80, 0x3d, 0x87, 0x40, 0xbb, 0x9f, 0x2f, 0xa9, 0x7f, 0xbe,
	0xff, 0x4b, 0xbf, 0x12, 0xbf, 0xba, 0xf9, 0x75, 0xf3, 0xeb, 0x4c, 0x76, 0xac, 0xfe, 0xe4, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x3f, 0xf0, 0xe4, 0xc7, 0x03, 0x00, 0x00,
}
