// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credential.proto

package credential_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credential struct {
	Data                 *Data         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Verification         *Verification `protobuf:"bytes,2,opt,name=verification,proto3" json:"verification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_4c441bc05f72453e, []int{0}
}
func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (dst *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(dst, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Credential) GetVerification() *Verification {
	if m != nil {
		return m.Verification
	}
	return nil
}

type Data struct {
	Template             *Template       `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	RecipientPub         string          `protobuf:"bytes,2,opt,name=recipient_pub,json=recipientPub,proto3" json:"recipient_pub,omitempty"`
	DateEarned           string          `protobuf:"bytes,3,opt,name=date_earned,json=dateEarned,proto3" json:"date_earned,omitempty"`
	CoreData             *_struct.Struct `protobuf:"bytes,4,opt,name=core_data,json=coreData,proto3" json:"core_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_4c441bc05f72453e, []int{1}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTemplate() *Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Data) GetRecipientPub() string {
	if m != nil {
		return m.RecipientPub
	}
	return ""
}

func (m *Data) GetDateEarned() string {
	if m != nil {
		return m.DateEarned
	}
	return ""
}

func (m *Data) GetCoreData() *_struct.Struct {
	if m != nil {
		return m.CoreData
	}
	return nil
}

type Verification struct {
	RecipientPub         string               `protobuf:"bytes,1,opt,name=recipient_pub,json=recipientPub,proto3" json:"recipient_pub,omitempty"`
	IssuerPub            string               `protobuf:"bytes,2,opt,name=issuer_pub,json=issuerPub,proto3" json:"issuer_pub,omitempty"`
	Signature            string               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	ProofOfIntegrityHash string               `protobuf:"bytes,4,opt,name=proof_of_integrity_hash,json=proofOfIntegrityHash,proto3" json:"proof_of_integrity_hash,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	RevocationStatus     *RevocationStatus    `protobuf:"bytes,6,opt,name=revocation_status,json=revocationStatus,proto3" json:"revocation_status,omitempty"`
	IpfsHash             string               `protobuf:"bytes,7,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Verification) Reset()         { *m = Verification{} }
func (m *Verification) String() string { return proto.CompactTextString(m) }
func (*Verification) ProtoMessage()    {}
func (*Verification) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_4c441bc05f72453e, []int{2}
}
func (m *Verification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verification.Unmarshal(m, b)
}
func (m *Verification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verification.Marshal(b, m, deterministic)
}
func (dst *Verification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verification.Merge(dst, src)
}
func (m *Verification) XXX_Size() int {
	return xxx_messageInfo_Verification.Size(m)
}
func (m *Verification) XXX_DiscardUnknown() {
	xxx_messageInfo_Verification.DiscardUnknown(m)
}

var xxx_messageInfo_Verification proto.InternalMessageInfo

func (m *Verification) GetRecipientPub() string {
	if m != nil {
		return m.RecipientPub
	}
	return ""
}

func (m *Verification) GetIssuerPub() string {
	if m != nil {
		return m.IssuerPub
	}
	return ""
}

func (m *Verification) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Verification) GetProofOfIntegrityHash() string {
	if m != nil {
		return m.ProofOfIntegrityHash
	}
	return ""
}

func (m *Verification) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Verification) GetRevocationStatus() *RevocationStatus {
	if m != nil {
		return m.RevocationStatus
	}
	return nil
}

func (m *Verification) GetIpfsHash() string {
	if m != nil {
		return m.IpfsHash
	}
	return ""
}

type RevocationStatus struct {
	IsRevoked            bool                 `protobuf:"varint,1,opt,name=isRevoked,proto3" json:"isRevoked,omitempty"`
	RevokedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=revokedAt,proto3" json:"revokedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RevocationStatus) Reset()         { *m = RevocationStatus{} }
func (m *RevocationStatus) String() string { return proto.CompactTextString(m) }
func (*RevocationStatus) ProtoMessage()    {}
func (*RevocationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_4c441bc05f72453e, []int{3}
}
func (m *RevocationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevocationStatus.Unmarshal(m, b)
}
func (m *RevocationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevocationStatus.Marshal(b, m, deterministic)
}
func (dst *RevocationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevocationStatus.Merge(dst, src)
}
func (m *RevocationStatus) XXX_Size() int {
	return xxx_messageInfo_RevocationStatus.Size(m)
}
func (m *RevocationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RevocationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RevocationStatus proto.InternalMessageInfo

func (m *RevocationStatus) GetIsRevoked() bool {
	if m != nil {
		return m.IsRevoked
	}
	return false
}

func (m *RevocationStatus) GetRevokedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Credential)(nil), "credential_pb.Credential")
	proto.RegisterType((*Data)(nil), "credential_pb.Data")
	proto.RegisterType((*Verification)(nil), "credential_pb.Verification")
	proto.RegisterType((*RevocationStatus)(nil), "credential_pb.RevocationStatus")
}

func init() { proto.RegisterFile("credential.proto", fileDescriptor_credential_4c441bc05f72453e) }

var fileDescriptor_credential_4c441bc05f72453e = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4d, 0x8f, 0xd3, 0x3c,
	0x10, 0xc7, 0xd5, 0x7d, 0xfa, 0x2c, 0xcd, 0x6c, 0x17, 0x8a, 0x01, 0x6d, 0xd5, 0x5d, 0x54, 0x54,
	0x0e, 0x70, 0xca, 0x8a, 0x37, 0x09, 0x71, 0x41, 0xbc, 0x49, 0x20, 0x21, 0x81, 0xbc, 0x2b, 0x0e,
	0x5c, 0x22, 0x27, 0x99, 0xb4, 0x86, 0x36, 0xb6, 0xec, 0x49, 0x05, 0x1f, 0x8c, 0xaf, 0xc1, 0x67,
	0x42, 0x9e, 0x24, 0x7d, 0xc9, 0x22, 0x6e, 0xce, 0x7f, 0x7e, 0x33, 0xf3, 0x9f, 0xb1, 0x03, 0xa3,
	0xcc, 0x61, 0x8e, 0x25, 0x69, 0xb5, 0x8c, 0xad, 0x33, 0x64, 0xc4, 0xf1, 0x56, 0x49, 0x6c, 0x3a,
	0x39, 0x9b, 0x1b, 0x33, 0x5f, 0xe2, 0x39, 0x07, 0xd3, 0xaa, 0x38, 0xf7, 0xe4, 0xaa, 0x8c, 0x6a,
	0x78, 0x72, 0x9d, 0x70, 0x65, 0x97, 0x8a, 0xb0, 0xf9, 0x9e, 0x76, 0x69, 0xd2, 0x2b, 0xf4, 0xa4,
	0x56, 0xb6, 0x06, 0x66, 0x6b, 0x80, 0x37, 0x9b, 0xfa, 0xe2, 0x01, 0xf4, 0x73, 0x45, 0x6a, 0xdc,
	0xbb, 0xd7, 0x7b, 0x78, 0xf4, 0xf8, 0x56, 0xbc, 0xd7, 0x3a, 0x7e, 0xab, 0x48, 0x49, 0x06, 0xc4,
	0x4b, 0x18, 0xae, 0xd1, 0xe9, 0x42, 0x67, 0x8a, 0xb4, 0x29, 0xc7, 0x07, 0x9c, 0x70, 0xda, 0x49,
	0xf8, 0xb2, 0x83, 0xc8, 0xbd, 0x84, 0xd9, 0xaf, 0x1e, 0xf4, 0x43, 0x3d, 0xf1, 0x08, 0x06, 0xad,
	0xe7, 0xa6, 0xed, 0x9d, 0xb8, 0x15, 0x42, 0x8d, 0xcb, 0xe6, 0x2c, 0x37, 0x98, 0xb8, 0x0f, 0xc7,
	0x0e, 0x33, 0x6d, 0x35, 0x96, 0x94, 0xd8, 0x2a, 0xe5, 0xee, 0x91, 0x1c, 0x6e, 0xc4, 0xcf, 0x55,
	0x2a, 0xa6, 0x70, 0x94, 0x87, 0x12, 0xa8, 0x5c, 0x89, 0xf9, 0xf8, 0x3f, 0x46, 0x20, 0x48, 0xef,
	0x58, 0x11, 0x4f, 0x21, 0xca, 0x8c, 0xc3, 0x84, 0x07, 0xee, 0x73, 0xe7, 0x93, 0xb8, 0x5e, 0x57,
	0xdc, 0xae, 0x2b, 0xbe, 0xe0, 0xe5, 0xca, 0x41, 0x20, 0x83, 0xdd, 0xd9, 0xef, 0x03, 0x18, 0xee,
	0x8e, 0x75, 0xd5, 0x4c, 0xef, 0x2f, 0x66, 0xee, 0x02, 0x68, 0xef, 0x2b, 0x74, 0x3b, 0x76, 0xa3,
	0x5a, 0x09, 0xe1, 0x33, 0x88, 0xbc, 0x9e, 0x97, 0x8a, 0x2a, 0x87, 0x8d, 0xd3, 0xad, 0x20, 0x9e,
	0xc1, 0x89, 0x75, 0xc6, 0x14, 0x89, 0x29, 0x12, 0x5d, 0x12, 0xce, 0x9d, 0xa6, 0x9f, 0xc9, 0x42,
	0xf9, 0x05, 0xdb, 0x8e, 0xe4, 0x6d, 0x0e, 0x7f, 0x2a, 0x3e, 0xb4, 0xc1, 0xf7, 0xca, 0x2f, 0xc4,
	0x0b, 0x00, 0xfc, 0x61, 0xb5, 0xab, 0x2f, 0xe8, 0x7f, 0x1e, 0x70, 0x72, 0x65, 0xc0, 0xcb, 0xf6,
	0x3d, 0xc8, 0x1d, 0x5a, 0x7c, 0x84, 0x9b, 0x0e, 0xd7, 0xa6, 0x1e, 0x31, 0xf1, 0xa4, 0xa8, 0xf2,
	0xe3, 0x43, 0x2e, 0x31, 0xed, 0xdc, 0xb1, 0xdc, 0x70, 0x17, 0x8c, 0xc9, 0x91, 0xeb, 0x28, 0xe2,
	0x14, 0x22, 0x6d, 0x0b, 0x5f, 0x5b, 0xbe, 0xc6, 0x96, 0x07, 0x41, 0x08, 0x36, 0x67, 0xdf, 0x60,
	0xd4, 0x2d, 0x11, 0xf6, 0xa1, 0x7d, 0x50, 0xbf, 0x63, 0xce, 0xfb, 0x1c, 0xc8, 0xad, 0x20, 0x9e,
	0x43, 0xe4, 0xea, 0xe3, 0x2b, 0x6a, 0x1e, 0xde, 0xbf, 0xe6, 0xda, 0xc2, 0xaf, 0x6f, 0x7c, 0xdd,
	0xff, 0x99, 0xd2, 0x43, 0xe6, 0x9f, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x93, 0xb6, 0xcb, 0x15,
	0x76, 0x03, 0x00, 0x00,
}
