// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction_receipts.proto

package badgeforce_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IssuingEngineReceipt struct {
	Date                 int64                   `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	StateAddress         string                  `protobuf:"bytes,2,opt,name=state_address,json=stateAddress,proto3" json:"state_address,omitempty"`
	RpcMethod            CredentialIssuingMethod `protobuf:"varint,3,opt,name=rpc_method,json=rpcMethod,proto3,enum=badgeforce_pb.CredentialIssuingMethod" json:"rpc_method,omitempty"`
	Credential           *Credential             `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *IssuingEngineReceipt) Reset()         { *m = IssuingEngineReceipt{} }
func (m *IssuingEngineReceipt) String() string { return proto.CompactTextString(m) }
func (*IssuingEngineReceipt) ProtoMessage()    {}
func (*IssuingEngineReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_receipts_4ca3a68e54b67fb4, []int{0}
}
func (m *IssuingEngineReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuingEngineReceipt.Unmarshal(m, b)
}
func (m *IssuingEngineReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuingEngineReceipt.Marshal(b, m, deterministic)
}
func (dst *IssuingEngineReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuingEngineReceipt.Merge(dst, src)
}
func (m *IssuingEngineReceipt) XXX_Size() int {
	return xxx_messageInfo_IssuingEngineReceipt.Size(m)
}
func (m *IssuingEngineReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuingEngineReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_IssuingEngineReceipt proto.InternalMessageInfo

func (m *IssuingEngineReceipt) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *IssuingEngineReceipt) GetStateAddress() string {
	if m != nil {
		return m.StateAddress
	}
	return ""
}

func (m *IssuingEngineReceipt) GetRpcMethod() CredentialIssuingMethod {
	if m != nil {
		return m.RpcMethod
	}
	return CredentialIssuingMethod_ISSUE
}

func (m *IssuingEngineReceipt) GetCredential() *Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func init() {
	proto.RegisterType((*IssuingEngineReceipt)(nil), "badgeforce_pb.IssuingEngineReceipt")
}

func init() {
	proto.RegisterFile("transaction_receipts.proto", fileDescriptor_transaction_receipts_4ca3a68e54b67fb4)
}

var fileDescriptor_transaction_receipts_4ca3a68e54b67fb4 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x89, 0x77, 0x08, 0x17, 0x3d, 0x3d, 0x82, 0xc5, 0xba, 0xd5, 0xa2, 0x20, 0x5b, 0x6d,
	0x71, 0x56, 0x96, 0x2a, 0x57, 0x58, 0xd8, 0xa4, 0xb4, 0x09, 0xb3, 0xc9, 0xb8, 0x06, 0xce, 0x24,
	0x4c, 0xc6, 0xc2, 0x9f, 0xe9, 0x3f, 0x12, 0x12, 0x51, 0xb7, 0xb8, 0xee, 0xf1, 0xf8, 0x78, 0xf9,
	0x32, 0xb2, 0x65, 0x82, 0x90, 0xc1, 0xb2, 0x8f, 0xc1, 0x10, 0x5a, 0xf4, 0x89, 0xf3, 0x90, 0x28,
	0x72, 0x54, 0xeb, 0x11, 0xdc, 0x84, 0xaf, 0x91, 0x2c, 0x9a, 0x34, 0xb6, 0x1b, 0x4b, 0xe8, 0x30,
	0xb0, 0x87, 0x7d, 0x05, 0xda, 0x8d, 0xf5, 0x26, 0xc1, 0xe7, 0x3e, 0x82, 0xab, 0xcd, 0xd5, 0x97,
	0x90, 0x17, 0x4f, 0x39, 0x7f, 0xf8, 0x30, 0xed, 0xc2, 0xe4, 0x03, 0xea, 0x3a, 0xa9, 0x94, 0x5c,
	0x3a, 0x60, 0x6c, 0x44, 0x27, 0xfa, 0x85, 0x2e, 0x59, 0x5d, 0xcb, 0x75, 0x66, 0x60, 0x34, 0xe0,
	0x1c, 0x61, 0xce, 0xcd, 0x51, 0x27, 0xfa, 0x95, 0x3e, 0x2d, 0xe5, 0x7d, 0xed, 0xd4, 0x4e, 0x4a,
	0x4a, 0xd6, 0xbc, 0x23, 0xbf, 0x45, 0xd7, 0x2c, 0x3a, 0xd1, 0x9f, 0x6d, 0x6f, 0x86, 0x99, 0xd9,
	0xf0, 0xf8, 0x2b, 0xf6, 0xf3, 0xf6, 0x73, 0xa1, 0xf5, 0x8a, 0x92, 0xad, 0x51, 0xdd, 0x49, 0xf9,
	0xa7, 0xdf, 0x2c, 0x3b, 0xd1, 0x9f, 0x6c, 0x2f, 0x0f, 0xce, 0xe8, 0x7f, 0xf0, 0xc3, 0xf9, 0xcb,
	0xfc, 0x10, 0xe3, 0x71, 0xf9, 0xeb, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x4b, 0xf1,
	0xca, 0x3c, 0x01, 0x00, 0x00,
}
