// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package issuer_pb is a generated protocol buffer package.

It is generated from these files:
	common.proto
	payload.proto
	issuance.proto
	degree.proto

It has these top-level messages:
	ProofOfIntegrity
	Payload
	AnyData
	Issuance
	AcademicCredential
	StorageHash
	Core
	VerifyHelperData
*/
package issuer_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProofOfIntegrity struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *ProofOfIntegrity) Reset()                    { *m = ProofOfIntegrity{} }
func (m *ProofOfIntegrity) String() string            { return proto.CompactTextString(m) }
func (*ProofOfIntegrity) ProtoMessage()               {}
func (*ProofOfIntegrity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProofOfIntegrity) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*ProofOfIntegrity)(nil), "issuer_pb.ProofOfIntegrity")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x2c, 0x2e, 0x2e, 0x4d, 0x2d,
	0x8a, 0x2f, 0x48, 0x52, 0x52, 0xe3, 0x12, 0x08, 0x28, 0xca, 0xcf, 0x4f, 0xf3, 0x4f, 0xf3, 0xcc,
	0x2b, 0x49, 0x4d, 0x2f, 0xca, 0x2c, 0xa9, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x48, 0x2c, 0xce, 0x90,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x3a, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x05, 0x7d, 0x57, 0x49, 0x00, 0x00, 0x00,
}
